---
title: "armc_5p2m"
format: html
---

```{r}
#Address
URL <-"https://ftp.ncbi.nlm.nih.gov/genomes/refseq/fungi/Saccharomyces_cerevisiae/latest_assembly_versions/GCF_000146045.2_R64/GCF_000146045.2_R64_genomic.fna.gz"

#Destenatoin file (output)

dest_file <- "GCF_000146045.2_R64_genomic.test.fna.gz"

#Download the file with wget
download.file(URL, method = "wget", destfile = dest_file)
```

```{r}
# 1. Uncompress and Read the raw NCBI file as simple text
con <- gzfile("GCF_000146045.2_R64_genomic.test.fna.gz", "rt")
ygen <- readLines(con)

close(con)  # <-- this is for closing the connection to the gz file, saves on resources. 



# 2. Define the new UCSC-style headers (chrI through chrXVI + chrM)
new_headers <- c(paste0(">chr", as.roman(1:16)), ">chrM")

# 3. Find and Replace
header_lines <- grep(">", ygen)
#Look at the header for chromosome 1
header_lines[1]

# Safety Check: Yeast has 16 nuclear chromosomes + 1 mitochondrial
if(length(header_lines) == 17) {
  ygen[header_lines] <- new_headers
  writeLines(ygen, "S288C_UCSC.fna")
  message("SUCCESS: Reference renamed to UCSC standards.")
} else {
  stop("Error: Chromosome count mismatch! Check your input file.")
}
```

```{bash}
flye --nano-raw "/Users/abatta00/Documents/BINF4010/Week2_Yeast_KM/ankur/clean_reads/ERR1539001_filtered.fastq.gz" --out-dir "ankur/assemble_genomes" --genome-size 12m -t 8 --scaffold -i 5
```

```{bash}
medaka_consensus -i "ankur/clean_reads/ERR1539001_filtered.fastq" -d "ankur/assemble_genomes/assembly.fasta" -o "ankur/polished_genomes" -t 8 
```

```{bash}
medaka_consensus -i "ankur/clean_reads/ERR1539001_filtered.fastq" -d "ankur/polished_genomes/consensus1.fasta" -o "ankur/polished_genomes" -t 8 
```

```{bash}
docker run quast -o " -r 
```

```{bash}
docker run --rm -v "$(pwd)":/data -w /data quay.io/biocontainers/quast:5.3.0--py313pl5321h5ca1c30_2 \
quast.py ankur/polished_genomes/consensus.fasta \
--fungus \
-r GCF_000146045.2_R64_genomic.test.fna \
-o reports/5_quast_output
```

```{bash}
docker run --rm \
-v "$PWD":/data \
-w /data \
ezlabgva/busco:v6.0.0_cv1 \
busco -i ankur/polished_genomes/consensus.fasta  -o reports/busco_output -m genome -c 8
```
