---
title: "Week2_Yeast_Quarto_KM"
author: "Kimia M"
format: html
editor: visual
---

# **Part 2: Long-Read Hygiene (Yeast Genome Project)**

## **Step 1: Project Setup (Separate Repo)**

## **Step 2: Data Acquisition**

```{r}
#| eval: false 
# 1. Create the data directory
dir.create("data/raw_reads", recursive = TRUE)

# 2. Define the download URL
yeast_url <- "ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR153/001/ERR1539001/ERR1539001.fastq.gz"

# 3. Download the file
# method="wget" is used for robustness with larger sequencing files
download.file(url = yeast_url, 
              destfile = "data/raw_reads/ERR1539001.fastq.gz", 
              method = "wget")

# 4. Verify the file is present
list.files("data/raw_reads/")
```

## **Step 3: The Audit & Filter (Replication)**

#### **Audit:** 

```{bash}
#| eval: false 
conda activate sequali_env

mkdir reports 

sequali data/raw_reads/ERR1539001.fastq.gz --outdir reports/pre_report
```

#### **Prepare Output Directory:**

```{r}
#| eval: false 
dir.create("data/clean_reads")
```

#### **Filter:**

```{bash}
#| eval: false 
filtlong --min_length 1000 --keep_percent 90 data/raw_reads/ERR1539001.fastq.gz | gzip > data/clean_reads/ont_filtered.fastq.gz
```

#### **Verify:** 

```{bash}
#| eval: false 
sequali data/clean_reads/ont_filtered.fastq.gz
```
